---
- hosts: all
- import_playbook: ../static-assignments/common.yml


- name: Loadbalancers assignment
       hosts: lb
         - import_playbook: ../static-assignments/loadbalancers.yml
        when: load_balancer_is_required

- hosts: uat-webservers
- import_playbook: ../static-assignments/uat-server.yml
